### ISSUE TITLE
propeller-gcc README.md quotes incorrectly "source fix_xcode_warnings.sh"

### ISSUE THREAD

**Issue by dgately** [dbetz/propeller-gcc#7]
The README.md documentation of propeller-ggc at the top level gives an incorrect naming for the file that fixes xcode warnings. Here's the incorrect text:

----------------------------------------------------------------------------------------
Also, the Xcode compiler seems to be more picky than the compilers on other platforms
so you will probably need to disable some warnings:

    source fix_xcode_warnings.sh                      **<== incorrect file name with underscores**
----------------------------------------------------------------------------------------

Should be:

  source fix-xcode-warnings.sh                     <== '-' dashes replace '_' underscores

If users copy/paste the uncorrected line into a terminal session, they'll get a failure: 

> -bash: fix_xcode_warnings.sh: No such file or directory

**Comment by dbetz** [comment]
Thanks for noticing. I've fixed this.
